[WIP] drifting turn
CityScope/CS_Cooper-Hewitt pull request #122
Opened 2018-12-01 16:56 UTC by ooookai

This PR makes agents turn/rotate smoothly.
I am just playing the code on my computer. I hope this helps.
However, I am not sure the variables I declared are named properly. Please let me know if there is a better way.

`afterNode` : the node on the path after toNode.

I will clean the code later.

2018-12-01 17:15 UTC, aberke requested changes

2018-12-01 17:15 UTC, aberke commented on ABMobility/Agent.pde
> +      if (pathIndex > 1){
Is this if statement redundant to line 198? I think you can/should remove it

2018-12-01 17:15 UTC, aberke commented on ABMobility/Agent.pde
> +          // p.rotate(dir.heading() + PI * 0.5);
Please don’t leave in commented out code

2018-12-01 17:16 UTC, aberke commented
This seems like a nice idea! Thanks for doing this

2018-12-02 22:25 UTC, yasushisakai commented
Looks good, I’m doing a bit of testing of this branch on my side too. As soon as I think it’s good I’ll merge. @ooookai thanks!

2018-12-03 09:27 UTC, merged